version: '2'

services:
  web_app1:
    restart: always
    build: ~/app1
    container_name: flaskapp_1
    command: >
        gunicorn -b :8000
         --access-logfile -
         --reload
         "app1.app:create_app()"
    volumes:
    - /host/dir/to/app:/static/app1
    expose:
      - "8000"

  web_app2:
    restart: always
    build: ~/app2
    container_name: flaskapp_2
    command: >
        gunicorn -b :8000
         --access-logfile -
         --reload
         "app2.app:create_app()"
    volumes:
    - /host/dir/to/app:/static/app2
    expose:
      - "8000"

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes_from:
      - web_app1
      - web_app2
    links:
    - web_app1:web_app1
    - web_app2:web_app2

